import ChatSideBar from "@/components/paitent/chat-side-bar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "MedOrbX | Patient Dashboard",
  description: "Generated by create next app",
};

export default function DoctorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <div className="flex fixed top-0 right-0 justify-center items-center min-h-screen mx-4">
        <ChatSideBar />
      </div>
      <div>{children}</div>
    </div>
  );
}
