import WalletConnectButton from "@/components/WalletConnectButton";
import SideBar from "@/components/docotr/SideBar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "MedOrbX | Doctor Dashboard",
  description: "Generated by create next app",
};

export default function DoctorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="min-h-screen bg-indigo-950">
      <SideBar />
      <div className="absolute top-10 right-10">
        <WalletConnectButton />
      </div>
      {children}
    </main>
  );
}
