import SideBar from "@/components/docotr/SideBar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "MedOrbX | Doctor Dashboard",
  description: "Generated by create next app",
};

export default function DoctorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main>
      <SideBar />
      {children}
    </main>
  );
}
