import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/Providers";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { GeistSans } from "geist/font/sans";
import { Toaster } from "react-hot-toast";
import MainNavBar from "@/components/MainNavBar";

export const metadata: Metadata = {
  title: "MedOrbX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  authModal,
}: {
  children: React.ReactNode;
  authModal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <Toaster />
        <Providers>
          <MainNavBar />
          {authModal}
          {children}
        </Providers>
        <SpeedInsights />
      </body>
    </html>
  );
}
