import WalletConnectButton from "@/components/WalletConnectButton";
import SideBar from "@/components/paitent/SideBar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "MedOrbX | Patient Dashboard",
  description: "Generated by create next app",
};

export default function DoctorLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="h-[100svh] md:h-screen bg-[radial-gradient(ellipse_at_left,_var(--tw-gradient-stops))] from-violet-950 via-indigo-950 to-blue-950">
      <SideBar />
      <div className="absolute top-6 right-10 z-[10]">
        <WalletConnectButton />
      </div>
      {children}
    </main>
  );
}
